apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: utils-apicurio-registry-uiyz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: utils-apicurio-registry-uiyz
    app.kubernetes.io/part-of: apicurio-registry-2-components
  name: utils-apicurio-registry-uiyz
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: utils-apicurio-registry-uiyz
status:
  loadBalancer: {}
